export const employeeDataList = [
    {
        id: 1,
        name: 'tester testy',
        department: 'Sales',
        phoneNumber: 'string',
        gender: 'Nam',
        email: 'test1@gmail.com',
        bank: 'string',
        birthday: '4 tháng 8 năm 2003',
        address: 'string',
        nationality: 'string',
        bankAccount: 'string',
    },
    {
        id: 2,
        name: 'Nguyen Van A',
        department: 'Chăm sóc khách hàng',
        phoneNumber: 'string',
        gender: 'Nam',
        email: 'test2@gmail.com',
        bank: 'string',
        birthday: '4 tháng 4 năm 2000',
        address: 'string',
        nationality: 'string',
        bankAccount: 'string',
    },
    {
        id: 3,
        name: 'Nguyen Van Nhan Vien',
        department: 'Sales',
        phoneNumber: 'string',
        gender: 'Nam',
        email: 'vnhd@gmail.com',
        bank: 'string',
        birthday: '24 tháng 8 năm 2002',
        address: 'string',
        nationality: 'string',
        bankAccount: 'string',
    },
    {
        id: 4,
        name: 'Vu Ngoc Hai Dang',
        department: 'Chăm sóc khách hàng',
        phoneNumber: 'string',
        gender: 'Nam',
        email: 'dangvnh@gmail.com',
        bank: 'string',
        birthday: '31 tháng 7 năm 2003',
        address: 'string',
        nationality: 'string',
        bankAccount: 'string',
    },
    {
        id: 5,
        name: 'Nguyen Thi Truong Phong',
        department: 'Sales',
        phoneNumber: 'string',
        gender: 'Nữ',
        email: 'admin@gmail.com',
        bank: 'string',
        birthday: '4 tháng 8 năm 1999',
        address: 'string',
        nationality: 'string',
        bankAccount: 'string',
    },
    {
        id: 6,
        name: 'Nguyen A',
        department: 'Chăm sóc khách hàng',
        phoneNumber: 'string',
        gender: 'Nữ',
        email: 'staff@gmail.com',
        bank: 'string',
        birthday: '17 tháng 5 năm 2001',
        address: 'string',
        nationality: 'string',
        bankAccount: 'string',
    },
]